// Generated by wrangler types / maintained manually.
// Add new Worker secrets/bindings here as they are created.
interface Env {
	/** GitHub fine-grained PAT — read-only, public repos. Set via: npx wrangler secret put GITHUB_TOKEN */
	GITHUB_TOKEN?: string;
	/** Cloudflare Workers AI binding for chat model inference. */
	AI: Ai;
	/** Durable Object namespace for the Sybil Proxy AI chat agent. */
	SybilProxyAgent: DurableObjectNamespace<import("./agent/sybil-proxy").SybilProxyAgent>;
}

// Provides types for the `cloudflare:workers` virtual module used in Astro v6 SSR.
// Use `import { env } from 'cloudflare:workers'` to access Worker bindings/secrets.
declare module 'cloudflare:workers' {
	const env: Env;
	export { env };
}
