// Generated by wrangler types / maintained manually.
// Add new Worker secrets/bindings here as they are created.
interface Env {
	/** GitHub fine-grained PAT — read-only, public repos. Set via: npx wrangler secret put GITHUB_TOKEN */
	GITHUB_TOKEN?: string;
	/** Optional durable object binding for the Sybil Proxy agent scaffold. */
	SybilProxyAgent?: DurableObjectNamespace;
}

// Provides types for the `cloudflare:workers` virtual module used in Astro v6 SSR.
// Use `import { env } from 'cloudflare:workers'` to access Worker bindings/secrets.
declare module 'cloudflare:workers' {
	const env: Env;
	export { env };
}
